Repository fluxcd/image-reflector-controller, pull requests merged in 2021-03, with the labels that each got.

#119 Fix "last scan" print column for ImageRepository
  api/v1alpha1/imagerepository_types.go
  config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
Labels: bug

#121 Update dependencies
  .github/workflows/fossa.yml
  .github/workflows/scan.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#125 Set leader election deadline to 30s
  go.mod
  go.sum
  main.go
Labels: enhancement

#126 fix github link for image-automation-controller
  docs/spec/v1alpha1/imagepolicies.md
Labels: documentation
