Repository fluxcd/image-reflector-controller, pull requests merged in 2021-02, with the labels that each got.

#100 Enable pprof endpoints on metrics server
  go.mod
  go.sum
  main.go
Labels: area/build

#101 Update Alpine to v3.13
  Dockerfile
  config/manager/deployment.yaml
Labels: area/build

#104 Implement numerical ordering policy
  api/v1alpha1/imagepolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
  internal/policy/alphabetical.go
  internal/policy/factory.go
  internal/policy/numerical.go
  internal/policy/numerical_test.go
Labels: enhancement

#106 Add numerical policy to API docs
  api/v1alpha1/imagepolicy_types.go
  docs/spec/v1alpha1/imagepolicies.md
Labels: documentation

#109 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#110 Refactor release workflow
  .github/workflows/release.yml
Labels: area/build
