Repository fluxcd/image-reflector-controller, pull requests merged in 2021-11, with the labels that each got.

#199 Fix watched same-ns image repos trigger reconcile
  controllers/imagepolicy_controller.go
  controllers/policy_test.go
Labels: bug

#204 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#205 Update github.com/opencontainers/image-spec v1.0.2
  go.mod
  go.sum
Labels: area/build

#189 Set default observedGeneration to -1
  api/v1beta1/imagepolicy_types.go
  api/v1beta1/imagerepository_types.go
  config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
  config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
Labels: enhancement
