Repository fluxcd/image-reflector-controller, pull requests merged in 2021-01, with the labels that each got.

#81 Add reference docs for API types
  docs/spec/v1alpha1/imagepolicies.md
  docs/spec/v1alpha1/imagerepositories.md
Labels: documentation, gotk

#83 Update Kubernetes packages to v1.20.2
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#84 Update Badger to v3.2011.0
  controllers/suite_test.go
  go.mod
  go.sum
  internal/database/badger.go
  internal/database/badger_test.go
  main.go
Labels: area/build

#88 Fix ARM build
  .github/workflows/build.yaml
  go.mod
  go.sum
Labels: area/build

#91 Update fluxcd/pkg/runtime to v0.8.0
  api/go.mod
  api/go.sum
  api/v1alpha1/imagepolicy_types.go
  api/v1alpha1/imagerepository_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
  config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
  controllers/policy_test.go
  controllers/scan_test.go
  go.mod
  go.sum
  main.go
Labels: area/build

#90 Add examples to the API spec docs
  docs/spec/v1alpha1/imagepolicies.md
  docs/spec/v1alpha1/imagerepositories.md
Labels: documentation

#95 Update BadgerDB to v3.2011.1
  go.mod
  go.sum
Labels: area/build

#97 Update ImagePolicy example
  docs/spec/v1alpha1/imagepolicies.md
Labels: documentation
