Repository fluxcd/image-reflector-controller, pull requests merged in 2022-05, with the labels that each got.

#252 Adds ServiceAccountName for ImageRepository API
  api/v1beta1/imagerepository_types.go
  config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
  config/rbac/role.yaml
  controllers/imagerepository_controller.go
  controllers/scan_test.go
  docs/api/image-reflector.md
  go.mod
  go.sum
Labels: enhancement

#253 Add service account name to API docs
  docs/spec/v1beta1/imagerepositories.md
Labels: area/docs

#254 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#256 Add `exclusionList` to enable excluding tags based on regex.
  .gitignore
  Makefile
  api/v1beta1/imagerepository_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
  controllers/imagerepository_controller.go
  controllers/scan_test.go
  docs/api/image-reflector.md
  docs/spec/v1beta1/imagerepositories.md
Labels: enhancement

#261 Update dependencies
  .github/workflows/build.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#262 Update Alpine to 3.16
  Dockerfile
  api/go.mod
  api/go.sum
Labels: area/build

#263 Release v0.19.0
  CHANGELOG.md
  config/manager/kustomization.yaml
  go.mod
Labels: area/build
