Repository fluxcd/image-reflector-controller, pull requests merged in 2023-07, with the labels that each got.

#410 Update Go dependencies
  go.mod
  go.sum
Labels: dependencies

#414 ci: various workflow changes
  .github/dependabot.yaml
  .github/workflows/backport.yaml
Labels: area/ci

#416 Fix GHA backport.yaml workflow job perms
  .github/workflows/backport.yaml
  .github/workflows/release.yml
Labels: area/ci

#417 Update `fluxcd/pkg/oci` to fix ECR cross-region auth
  go.mod
  go.sum
Labels: dependencies, area/oci
