Repository fluxcd/image-reflector-controller, pull requests merged in 2023-06, with the labels that each got.

#400 Add SLSA3 generators to release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: area/build

#401 Align `go.mod` version with Kubernetes (Go 1.20)
  api/go.mod
  go.mod
  tests/fuzz/Dockerfile.builder
Labels: area/build

#405 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#406 Add backport GitHub Action workflow
  .github/dependabot.yaml
  .github/labels.yaml
  .github/workflows/backport.yaml
  .github/workflows/sync-labels.yaml
Labels: enhancement, area/build
