Repository fluxcd/image-reflector-controller, pull requests merged in 2025-05, with the labels that each got.

#761 Downgrade k8s.io/utils and github.com/Masterminds/semver
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#368 Store digest of latest image in ImagePolicy status
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/condition_types.go
  api/v1beta2/imagepolicy_types.go
  api/v1beta2/imagerepository_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
  docs/api/v1beta2/image-reflector.md
  docs/spec/v1beta2/imagepolicies.md
  hack/boilerplate.go.txt
  internal/controller/imagepolicy_controller.go
  internal/controller/imagepolicy_controller_test.go
  internal/controller/imagerepository_controller.go
  internal/controller/imagerepository_controller_test.go
  internal/controller/policy_test.go
  internal/controller/scan_test.go
  internal/controller/suite_test.go
  internal/registry/helper.go
  internal/registry/options.go
  internal/registry/options_test.go
  internal/test/registry.go
  internal/test/registry_test.go
  main.go
  tests/integration/gcp_test.go
  tests/integration/go.mod
  tests/integration/imagerepo_and_policy_test.go
  tests/integration/terraform/gcp/outputs.tf
Labels: enhancement

#764 Update controller-runtime to v0.21.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#765 Update dependencies
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#766 [RFC-0010] Link workload identity docs to complete guide
  docs/spec/v1beta2/imagerepositories.md
Labels: area/docs
